# Generated by Django 2.0.1 on 2018-02-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_auto_20180202_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'MASCULINO'), ('femenino', 'FEMENINO')], max_length=50),
        ),
    ]
